# -*- mode: ruby -*-
# vi: set ft=ruby : 
require_relative 'vagrant_credentials.rb'
include Secrets

#-------------
GUI = false
MEMORY = "4096"
CPU = 4
#-------------

update = <<-SHELL
  echo [disabled PasswordAuthentication and SELINUX]
  sed -i 's/PasswordAuthentication\s.*no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  systemctl disable firewalld
  systemctl restart sshd
  sudo setenforce 0
  sudo sed -i s/SELINUX=enforcing/SELINUX=disabled/ /etc/sysconfig/selinux
  mkdir /log
  echo [UPDATE SYSTEM AND MIRRORS]
  sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
  sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
  echo [INSTALL PACAGES]
  dnf install -y git wget >> /log/connect.log 2>>/log/connect_error.log
  wget https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/s/sshpass-1.06-1.el7.x86_64.rpm >> /log/connect.log 2>>/log/connect_error.log
  sudo rpm -Uvh sshpass* >> /log/connect.log 2>>/log/connect_error.log
  sudo yum install -y sshpass >> /log/connect.log 2>>/log/connect_error.log
SHELL

test_connect = <<-SHELL
  echo [TEST INTERNET]
  curl -I https://linuxconfig.org 2>/dev/null
SHELL

k3s_master = <<-SHELL
  echo [RUN K3S SERVER]
  curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 644 --flannel-iface=eth1 
  systemctl status k3s.service > k3s_status
  cat k3s_status
  rm -rf k3s_status
  cp /var/lib/rancher/k3s/server/token /home/vagrant
  sudo chmod 777 /home/vagrant/token
SHELL

change_pass = <<-SHELL
  echo [CHANGE PASS]
  echo $1 | sudo passwd --stdin vagrant
  echo $1 | sudo passwd --stdin root
SHELL


start_kub = <<-SHELL
    echo [RUN ingress controller]
    git clone https://github.com/nginxinc/kubernetes-ingress.git --branch v2.3.0
    cd kubernetes-ingress/deployments
    /usr/local/bin/kubectl apply -f common/ns-and-sa.yaml
    /usr/local/bin/kubectl apply -f rbac/rbac.yaml
    /usr/local/bin/kubectl apply -f common/default-server-secret.yaml
    /usr/local/bin/kubectl apply -f common/nginx-config.yaml
    /usr/local/bin/kubectl apply -f common/ingress-class.yaml
    /usr/local/bin/kubectl apply -f common/crds/k8s.nginx.org_virtualservers.yaml
    /usr/local/bin/kubectl apply -f common/crds/k8s.nginx.org_virtualserverroutes.yaml
    /usr/local/bin/kubectl apply -f common/crds/k8s.nginx.org_transportservers.yaml
    /usr/local/bin/kubectl apply -f common/crds/k8s.nginx.org_policies.yaml
    /usr/local/bin/kubectl apply -f deployment/nginx-ingress.yaml
    /usr/local/bin/kubectl create -f service/nodeport.yaml
    echo [RUN YAMLs on MASTER]
    /usr/local/bin/kubectl create ns app
    /usr/local/bin/kubectl apply -f /vagrant/configs/apps.yaml
    /usr/local/bin/kubectl apply -f /vagrant/configs/services.yaml
    /usr/local/bin/kubectl apply -f /vagrant/configs/ingress.yaml
    /usr/local/bin/kubectl get all -ALL
SHELL



#TODO del mashine 2
#TODO NAME

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.define "AtweekS" do |config|
    config.vm.hostname = "AtweekS"
    config.vm.network :private_network, ip: "192.168.42.111"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = GUI
      vb.memory = MEMORY
      vb.cpus = CPU
      vb.name = "AtweekS"
    end
    config.vm.provision "shell", inline: test_connect
    config.vm.provision "shell", inline: update
    config.vm.provision "shell", inline: k3s_master
    config.vm.provision "shell", inline: change_pass, args: Password
    config.vm.provision "shell", inline: start_kub, args: Password    
  end
end

