# -*- mode: ruby -*-
# vi: set ft=ruby : 
require_relative 'vagrant_credentials.rb'
include Secrets

#-------------
GUI = false
MEMORY = "4096"
CPU = 4
#-------------

update = <<-SHELL
  echo [disabled PasswordAuthentication and SELINUX]
  sed -i 's/PasswordAuthentication\s.*no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  systemctl disable firewalld
  systemctl restart sshd
  sudo setenforce 0
  sudo sed -i s/SELINUX=enforcing/SELINUX=disabled/ /etc/sysconfig/selinux
  mkdir /log
  echo [UPDATE SYSTEM AND MIRRORS]
  sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
  sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
  echo [INSTALL PACAGES]
  dnf install -y wget >> /log/connect.log 2>>/log/connect_error.log
  wget https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/s/sshpass-1.06-1.el7.x86_64.rpm >> /log/connect.log 2>>/log/connect_error.log
  sudo rpm -Uvh sshpass* >> /log/connect.log 2>>/log/connect_error.log
  sudo yum install -y sshpass >> /log/connect.log 2>>/log/connect_error.log
SHELL

test_connect = <<-SHELL
  echo [TEST INTERNET]
  curl -I https://linuxconfig.org 2>/dev/null
SHELL

k3s_master = <<-SHELL
  echo [RUN K3S SERVER]
  curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 644 --flannel-iface=eth1 >> /log/k3s.log 2>>/log/k3s_error.log
  systemctl status k3s.service > k3s_status
  cat k3s_status
  rm -rf k3s_status
  cp /var/lib/rancher/k3s/server/token /home/vagrant
  sudo chmod 777 /home/vagrant/token
SHELL

ssh = <<-SHELL
  echo [CHANGE PASS]
  echo $1 | sudo passwd --stdin vagrant
  echo $1 | sudo passwd --stdin root
SHELL

k3s_node = <<-SHELL
  echo [RUN K3S NODE]
  export SSHPASS=$1
  sshpass -e scp -o StrictHostKeyChecking=no vagrant@192.168.42.111:/home/vagrant/token ./
  sudo chmod 777 /home/vagrant/token
  curl -sfL https://get.k3s.io | sh -s - agent --server=https://192.168.42.111:6443  --token-file=/home/vagrant/token --flannel-iface=eth1
  systemctl status k3s-agent.service > k3s_status
  cat k3s_status
  rm -rf k3s_status
SHELL



Vagrant.configure("2") do |config|
  config.vm.box = "centos/8" #7
  config.vm.define "AtweekS" do |config|
    config.vm.hostname = "AtweekS"
    config.vm.network :private_network, ip: "192.168.42.111"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = GUI
      vb.memory = MEMORY
      vb.cpus = CPU
      vb.name = "AtweekS"
    end
    config.vm.provision "shell", inline: test_connect
    config.vm.provision "shell", inline: update
    config.vm.provision "shell", inline: k3s_master
    config.vm.provision "shell", inline: ssh, args: Password
  end
  config.vm.define "AtweekSW" do |config|
    config.vm.hostname = "AtweekSW"
    config.vm.network :private_network, ip: "192.168.42.110"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = GUI
      vb.name = "AtweekSW"
      vb.memory = MEMORY
      vb.cpus = CPU
    end
    config.vm.provision "shell", inline: test_connect
    config.vm.provision "shell", inline: update
    config.vm.provision "shell", inline: ssh, args: Password
    config.vm.provision "shell", inline: k3s_node, args: Password
  end
end

