apiVersion: apps/v1
kind: Deployment
metadata:
  name: atweek
  labels:
    app: playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: atweek
spec:
  type: NodePort
  selector:
    app: playground
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30000