# -*- mode: ruby -*-
# vi: set ft=ruby : 

require_relative 'vagrant_credentials.rb'
include Secrets

server_script = <<-SHELL
  mkdir 1
  cp -r 1 /vagrant
  cp -r 1 /vagrant/shared
SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.define "Server" do |config|
    config.vm.hostname = "Server"
    config.vm.network :private_network, ip: "192.168.42.111"
    config.vm.synced_folder "./shared", "/vagrant_shared"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "Server"
    end
    # config.vm.provision "shell", inline: server_script
  end
  config.vm.define "ServerWorker" do |config|
    config.vm.hostname = "ServerWorker"
    config.vm.network :private_network, ip: "192.168.42.110"
    config.vm.synced_folder "./shared", "/vagrant_shared"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "ServerWorker"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end

