---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: paulbouwer/hello-kubernetes:1
        ports:
          - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello from app1"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: paulbouwer/hello-kubernetes:1
        ports:
          - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello from app2"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app3
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: paulbouwer/hello-kubernetes:1
        ports:
          - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello from app3"
---