apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: argocd.atweek

  accounts.atweek: apiKey, login
  accounts.atweek.enabled: "true"

  repositories: |
    - type: git
      url: https://github.com/atweek/Inception-of-Things